AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Launch t2.micro/t3.micro EC2 instance with admin IAM role and deploy Django project.

Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t2.micro
      - t3.micro
    Description: EC2 instance type.

Resources:
  # IAM Role
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2AdminRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  # Security Group
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, and HTTPS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0323cb4d7f1c0e3a2  # Latest Amazon Linux 2 AMI
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: key  # <-- Replace with your key pair name
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y python3 git
          curl -O https://bootstrap.pypa.io/get-pip.py
          python3 get-pip.py
          pip3 install virtualenv
          python3 -m virtualenv /home/ec2-user/venv
          source /home/ec2-user/venv/bin/activate
          pip install django gunicorn
          git clone https://github.com/mohamedhamednour/ajax-django-aws /home/ec2-user/store
          cd /home/ec2-user/store
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          python3 manage.py migrate
          python3 manage.py runserver 0.0.0.0:8000 &
      Tags:
        - Key: Name
          Value: DjangoEC2

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
  PublicIP:
    Description: Public IP Address
    Value: !GetAtt EC2Instance.PublicIp
